# Generated by Django 5.0.6 on 2024-07-04 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('preview_image1', models.ImageField(default=None, upload_to='images/')),
                ('preview_image2', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone_number', models.CharField(default=None, max_length=15)),
                ('github', models.CharField(default=None, max_length=255)),
                ('linkedin', models.CharField(default=None, max_length=255)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Resume.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default=None, max_length=255)),
                ('duration_from', models.DateField(default=None)),
                ('duration_to', models.DateField(default=None)),
                ('marks', models.CharField(default=None, max_length=255)),
                ('location', models.TextField(default=None)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to='Resume.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default=None, max_length=255)),
                ('marks', models.CharField(default=None, max_length=255)),
                ('location', models.TextField(default=None)),
                ('duration_from', models.DateField(default=None)),
                ('duration_to', models.DateField(default=None)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediates', to='Resume.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default=None)),
                ('duration_from', models.DateField(default=None)),
                ('duration_to', models.DateField(default=None)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Resume.detail')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default=None, max_length=255)),
                ('marks', models.CharField(default=None, max_length=255)),
                ('location', models.CharField(default=None, max_length=255)),
                ('duration', models.DateField(default=None)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='Resume.detail')),
            ],
        ),
        migrations.CreateModel(
            name='UiApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default=None)),
                ('technologies', models.TextField(default=None)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_applications', to='Resume.detail')),
            ],
        ),
    ]
