# Generated by Django 5.0.6 on 2024-07-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
