# Generated by Django 5.0.6 on 2024-07-05 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation', to='Resume.detail'),
        ),
        migrations.AlterField(
            model_name='intermediate',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate', to='Resume.detail'),
        ),
        migrations.AlterField(
            model_name='school',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='Resume.detail'),
        ),
    ]
