# Generated by Django 5.0.6 on 2024-07-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_alter_graduation_detail_alter_intermediate_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduation',
            old_name='college',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='intermediate',
            old_name='college',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school',
            new_name='name',
        ),
    ]
