# Generated by Django 5.0.6 on 2024-07-05 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_rename_college_graduation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workexperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('company_name', models.CharField(default=None)),
                ('duration_from', models.DateField(default=None)),
                ('duration_to', models.DateField(default=None)),
                ('description', models.TextField(default=None)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='Resume.detail')),
            ],
        ),
    ]
